test action7

diff --git a/.github/workflows/latex_to_pdf.yaml b/.github/workflows/latex_to_pdf.yaml
--- a/.github/workflows/latex_to_pdf.yaml
+++ b/.github/workflows/latex_to_pdf.yaml
@@ -2,9 +2,8 @@
 name: LaTeX to PDF
 on:
   push:
-    tags:
-      # YYYY-MM-DD
-      - "[0-9]{4}-[0-9]{2}-[0-9]{2}"
+    branches:
+      - main
 
 permissions:
   contents: write
@@ -15,6 +14,18 @@ jobs:
     steps:
       - name: Checkout repository
         uses: actions/checkout@v2
+      - name: Verify Commit Message Format
+        id: check_date
+        env:
+          COMMIT_MSG: ${{ github.event.head_commit.message }}
+        run: |
+          if [[ "$COMMIT_MSG" =~ ^[0-9]{4}-[0-9]{2}-[0-9]{2}$ ]]; then
+            echo "✅ Commit message valid: $COMMIT_MSG"
+            echo "date=$COMMIT_MSG" >> $GITHUB_OUTPUT
+          else
+            echo "❌ Error: Commit message '$COMMIT_MSG' does not match format yyyy-mm-dd"
+            exit 1
+          fi
       - name: Compile LaTeX to PDF
         uses: xu-cheng/latex-action@v4
         with:
@@ -29,7 +40,8 @@ jobs:
         uses: softprops/action-gh-release@v2
         with:
           files: main.pdf
-          tag_name: ${{ github.ref_name }}
+          name: "Appunti HCI - ${{ steps.check_date.outputs.date }}"
+          tag_name: ${{ steps.check_date.outputs.date }}
           draft: false
           prerelease: false
           overwrite_files: true
